#!/bin/bash

# Create symlinks to *.ini files in folder /etc/php_custom for custom php.ini settings
if [ -e /etc/php_custom ]; then
  if [ ! -z "$(find /etc/php_custom -name '*.ini')" ]; then
    for file in /etc/php_custom/*.ini ; do
      if [ -e /etc/php/conf.d/$(basename ${file}) ]; then
        rm -f /etc/php/conf.d/$(basename ${file})
      fi
      ln -sf ${file} /etc/php/conf.d/99_$(basename ${file})
    done
  fi
fi

# Create logdir if not existing
LOGDIR="/var/log/php-fpm"
if [ ! -e "${LOGDIR}" ]; then
  mkdir -p "${LOGDIR}"
fi
chmod 777 "${LOGDIR}"

# Add template files to /etc/php/fpm.d/ if not already existing
for file in /templates/??_* ; do
  if [ ! -e /etc/php/fpm.d/$(basename ${file}) ]; then
    cp -f "${file}" /etc/php/fpm.d/$(basename ${file})
  fi
done

# If exist, execute /extra/init . Must exit and not stay in front
if [ -e "/extra/init" ]; then
  if [ ! -x "/extra/init" ]; then
    chmod +x "/extra/init"
  fi
  /extra/init
fi

# Start PHP-FPM
cp -f /templates/php-fpm.conf /etc/php/php-fpm.conf
/usr/sbin/php-fpm -t && /usr/sbin/php-fpm -F -R
